### ISSUE TITLE
ls: impossible d'accéder à './temp/dataset_42017/*.txt': Aucun fichier ou dossier de ce type

### ISSUE THREAD

**Issue by cahaisv** [IARCbioinfo/mutspec#9]
$listAVDB is not initialized.

add line 59 :
$listAVDB = "$pathAVDBList/${refGenome}_listAVDB.txt";

**Comment by maudeardin** [comment]
Fix the initialisation of $listAVDB using Vincent modification.
Add a test for verifying the correct initialisation of $listAVDB.
